repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: .+\.csv
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["src/trailwatch/"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: scripts/code-quality/run-pylint.sh
        language: system
        pass_filenames: false
        types: [python]
      - id: bandit
        name: bandit
        entry: scripts/code-quality/run-bandit.sh
        language: system
        pass_filenames: false
        types: [python]
      - id: test
        name: test
        entry: scripts/test.sh
        language: system
        pass_filenames: false
        always_run: true
