FROM mcr.microsoft.com/vscode/devcontainers/python:3.10-buster

SHELL ["/bin/bash", "-c"]

# Install poetry
RUN python -m pip install --upgrade pip
RUN curl -sSL https://install.python-poetry.org | python3 -
